=== Moantonio/eia09/trunk/EIA09-Swing/plantillas/listaAcciones.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT listaAcciones (accion)+>
	<!ELEMENT accion (nombreAccion,listaAcciones?)>
	<!ELEMENT nombreAccion (#PCDATA)>

=== Moantonio/eia09/trunk/EIA09-Swing/plantillas/accionesVertedero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaAcciones SYSTEM ".\listaAcciones.dtd">
	<listaAcciones>
		<accion>
			<nombreAccion>Fase de Planeamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Diseño y localización de alternativas</nombreAccion>
				</accion>
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de construcción</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Excavaciones</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Eliminación cubierta terrestre y vegetación</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Movimiento de tierras</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Alteración hidrología</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Alteración drenaje</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Producción de ruidos y vibraciones</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Capa impermeabilizadota</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Construcción edificios auxiliares</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Instalación planteas de tratamiento</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Vías de acceso</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Presupuesto inversión</nombreAccion>
				</accion>
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de Funcionamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Transporte</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Recogida de residuos sólidos</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Almacenamiento y vertido</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Lixiviados</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Recubrimientos de tierra</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Pre-tratamiento de residuos</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Tratamiento de residuos</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Funcionamiento planta incineradora</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Olores</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Vapores, humos y polvos emitidos a la atmósfera</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Producción de ruidos y vibraciones </nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Obtención productos recuperables y reciclado</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Residuos del horno</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Incendios</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Coste económico</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Beneficio económico (productos recuperables)</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Composición y producción de residuos</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Metales</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Metales pesados</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Vidrio</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Restos reparaciones</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Tierras</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Materia orgánica</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Papel</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Cartón</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Plásticos</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Madera</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Goma</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Textiles</nombreAccion>
						</accion>
						
						<accion>
							<nombreAccion>Productos persistentes en las cadenas tróficas</nombreAccion>
						</accion>
						
						<accion>
							<nombreAccion>Pilas, Baterías de coche y residuos electrónicos </nombreAccion>
						</accion>						
						
						<accion>
							<nombreAccion>Insecticidas y pesticidas</nombreAccion>
						</accion>
						
						<accion>
							<nombreAccion>Productos tóxicos y/o radiactivos</nombreAccion>
						</accion>				
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Otras Características de las basuras</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Densidad</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Poder calorífico</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Humedad</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Relación carbono/hidrógeno</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Acciones inducidas</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Decremento del valor del suelo</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Decremento del comercio de la zona</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
			</listaAcciones>
		</accion>
	</listaAcciones>

=== Moantonio/eia09/trunk/EIA09-Swing/plantillas/accionesPresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaAcciones SYSTEM ".\listaAcciones.dtd">
	<listaAcciones>
		<accion>
			<nombreAccion>Fase de Planeamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Diseño y localización de alternativas</nombreAccion>
				</accion>
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de Construcción</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Desviación de aguas y ataguías</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Caminos y pistas de acceso y montaje</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Infraestructuras</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Líneas de transporte eléctrico</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Canales</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Conducciones de agua</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Obras de construcción propiamente dichas</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Transporte de materiales</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Movimiento de maquinaria pesada</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Vertido de tierras y otros materiales</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Edificios de obra</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Deforestación del vaso</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Explotación canteras</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Reposición de viales destruidos o inundados</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Expropiaciones</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Presupuesto económico de la obra</nombreAccion>
				</accion>
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de Funcionamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Presa y embalsamado del agua</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Infraestructuras  </nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Oscilaciones del nivel de agua embalsada</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Regulación del caudal de aguas abajo de la presa</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Acciones inducidas</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Aparición de urbanizaciones</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Incremento del valor del suelo</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Incremento del comercio de la zona</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
			</listaAcciones>
		</accion>
	</listaAcciones>
