=== Moantonio/eia09/EIASwing/plantillas/alternativaProyEIA.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT alternativaProyEIA (nombre, listaAcciones, listaEfectos?, valorTotalAlternativa?, valorada)>
<!ELEMENT nombre (#PCDATA)>
	<!ATTLIST nombre
	generica (true|false) "false">	
<!ELEMENT listaAcciones (accion)+>
	<!ELEMENT accion (nombreAccion,listaAcciones?)>
	<!ELEMENT nombreAccion (#PCDATA)>

<!ELEMENT listaEfectos (efecto)+>
<!ELEMENT efecto (idEfecto, descripcion, caracter, idAccion, idFactor, 			        valorSimpleEnjuiciamiento?, valorCuantitativo?,valorCualitativo?, valorTotal?)>
	<!ELEMENT idEfecto (#PCDATA)>
	<!ELEMENT descripcion (#PCDATA)>
	<!ELEMENT caracter (#PCDATA)>
	<!ELEMENT idAccion (#PCDATA)>
	<!ELEMENT idFactor (#PCDATA)>
	<!ELEMENT valorSimpleEnjuiciamiento (#PCDATA)>
	<!ELEMENT valorCuantitativo (indicador, maxVal, minVal, magnitud)>
		<!ELEMENT indicador (#PCDATA)>
		<!ELEMENT maxVal (#PCDATA)>
		<!ELEMENT minVal (#PCDATA)>
		<!ELEMENT magnitud (#PCDATA)>
	<!ELEMENT valorCualitativo (signo, acumulacion, extension, extensionCritica, intensidad, persistencia, reversibilidad, recuperabilidad, periodicidad, momento, momentoCritico, efectoImp, incidencia)>
		<!ELEMENT signo (#PCDATA)>
		<!ELEMENT acumulacion (#PCDATA)>
		<!ELEMENT extension (#PCDATA)>
		<!ELEMENT extensionCritica (#PCDATA)>
		<!ELEMENT intensidad (#PCDATA)>
		<!ELEMENT persistencia (#PCDATA)>
		<!ELEMENT reversibilidad (#PCDATA)>
		<!ELEMENT recuperabilidad (#PCDATA)>
		<!ELEMENT periodicidad (#PCDATA)>
		<!ELEMENT momento (#PCDATA)>
		<!ELEMENT momentoCritico (#PCDATA)>
		<!ELEMENT efectoImp (#PCDATA)>
		<!ELEMENT incidencia (#PCDATA)>
	
	<!ELEMENT valorTotal (#PCDATA)>
	<!ELEMENT valorada (#PCDATA)>
<!ELEMENT valorTotalAlternativa (#PCDATA)>

=== Moantonio/eia09/EIASwing/src/eia/util/xml/plantillas/alternativaVia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alternativaProyEIA SYSTEM ".\alternativaProyEIA.dtd">
<alternativaProyEIA>
	<nombre generica="true"></nombre>
	<listaAcciones>
		<accion>
			<nombreAccion>Fase de Planeamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Diseño</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Diseño del trazado</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Objetivos y fines del proyecto</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Localización</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Localización del eje viario</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Localización de prestamos y caballeros</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Localización de parques de maquinaria y oficinas</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de Construcción</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Expropiaciones</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Expropiaciones</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Explanaciones y Movimiento de tierras</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Desbroce y despeje</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Excavación y acopio tierra vegetal</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Excavaciones en desmontes</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Terraplenes y pedraplenes</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Voladuras y perforaciones</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Préstamos y vertederos</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Demolición de edificios que interfieren</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Desvío de servicios y obras temporales</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Afirmado</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Instalación plantas de obra para firmes</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Riesgos bituminosos y/o curado</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>	
				<accion>
					<nombreAccion>Estructuras, obras de fábrica y drenajes</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Construcción de puentes y túneles</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Construcción de pasos elevados y subterráneos</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Desvíos y canalizaciones de cauces de aguas</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Obras de drenaje longitudinal y transversal</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Obras y trabajos auxiliares</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Ordenación y desvío del trafico</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Señalización</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Revegetación, cerramientos e iluminación</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Caminos de servicio</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Fase de construcción</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Fase de construcción</nombreAccion>
						</accion>						
						<accion>
							<nombreAccion>Ocupación por la vía</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>	
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de Funcionamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Tráfico</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Emisión de ruido</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Vibraciones</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Contaminaciones</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Trafico rodado</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Mantenimiento</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Uso de sales</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Herbicidas y aditivos para la conservación</nombreAccion>
						</accion>
							<accion>
							<nombreAccion>Aparición de escombreras</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
			</listaAcciones>
		</accion>
	</listaAcciones>
</alternativaProyEIA>

=== Moantonio/eia09/EIASwing/plantillas/alternativaVertedero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alternativaProyEIA SYSTEM ".\alternativaProyEIA.dtd">
<alternativaProyEIA>
	<nombre generica="true"></nombre>
	<listaAcciones>
		<accion>
			<nombreAccion>Fase de Planeamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Diseño y localización de alternativas</nombreAccion>
				</accion>
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de construcción</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Excavaciones</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Eliminación cubierta terrestre y vegetación</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Movimiento de tierras</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Alteración hidrología</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Alteración drenaje</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Producción de ruidos y vibraciones</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Capa impermeabilizadota</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Construcción edificios auxiliares</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Instalación planteas de tratamiento</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Vías de acceso</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Presupuesto inversión</nombreAccion>
				</accion>
			</listaAcciones>
		</accion>
		
		<accion>
			<nombreAccion>Fase de Funcionamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Transporte</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Recogida de residuos sólidos</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Almacenamiento y vertido</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Lixiviados</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Recubrimientos de tierra</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Pre-tratamiento de residuos</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Tratamiento de residuos</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Funcionamiento planta incineradora</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Olores</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Vapores, humos y polvos emitidos a la atmósfera</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Producción de ruidos y vibraciones</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Obtención productos recuperables y reciclado</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Residuos del horno</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Incendios</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Coste económico</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Beneficio económico (productos recuperables)</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Presencia de insectos roedores y aves</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Composición y producción de residuos</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Metales</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Vidrio</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Restos reparaciones</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Tierras</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Materia orgánica</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Papel</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Cartón</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Plásticos</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Madera</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Goma</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Textiles</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
				<accion>
					<nombreAccion>Otras Características de las basuras</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Densidad</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Poder calorífico</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Humedad</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Relación carbono/hidrógeno</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
			</listaAcciones>
		</accion>
	</listaAcciones>
</alternativaProyEIA>

=== Moantonio/eia09/EIASwing/plantillas/alternativaPuerto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alternativaProyEIA SYSTEM ".\alternativaProyEIA.dtd">
<alternativaProyEIA>
	<nombre generica="true"></nombre>
	<listaAcciones>
		<accion>
			<nombreAccion>Fase de Planeamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Diseño y localización de alternativas</nombreAccion>
				</accion>
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de Construcción</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Ampliación superficie ganada al mar</nombreAccion>
				</accion>				
				<accion>
					<nombreAccion>Relleno</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Dragado</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Diques</nombreAccion>
				</accion>				
				<accion>
					<nombreAccion>Espigones</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Muelles</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Edificaciones</nombreAccion>
				</accion>				
				<accion>
					<nombreAccion>Viales</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Producción de ruido</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Emisión de polvo</nombreAccion>
				</accion>				
				<accion>
					<nombreAccion>Introducciones flora</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Uso maquinaria</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Alteración cubierta terrestre</nombreAccion>
				</accion>				
				<accion>
					<nombreAccion>Explotación de canteras</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Presupuesto económico de la obra</nombreAccion>
				</accion>
			</listaAcciones>
		</accion>
		<accion>
			<nombreAccion>Fase de Funcionamiento</nombreAccion>
			<listaAcciones>
				<accion>
					<nombreAccion>Navegación</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Edificios-servicio club</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Actividades comerciales</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Actividades industriales (reparaciones)</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Actividades sociales</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Actividades educativas</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Viales-tráfico</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Abastecimiento agua</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Saneamiento</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Vertidos al mar</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Residuos líquidos (aceite)</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Afluencia de visitantes</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Coste Anual de explotación y mantenimiento</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Accidentes propios de funcionamiento (empleo, riesgos de accidente)</nombreAccion>
				</accion>
				<accion>
					<nombreAccion>Acciones inducidas</nombreAccion>
					<listaAcciones>
						<accion>
							<nombreAccion>Aparición  de urbanizaciones</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Incremento del valor del suelo</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Incremento del suelo</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Incremento del comercio de la zona</nombreAccion>
						</accion>
						<accion>
							<nombreAccion>Edificios náuticos auxiliares</nombreAccion>
						</accion>
					</listaAcciones>
				</accion>
			</listaAcciones>
		</accion>
	</listaAcciones>
</alternativaProyEIA>
