=== Moantonio/eia09/EIASwing/plantillas/proyectoEIA.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT proyectoEIA (nombre, descripcion, promotor, redactor, fecha, vidaUtil,poblacion, provincia, pais, tipo, listaAlternativas, listaFactores, valorTotal?)>
	
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT promotor (#PCDATA)>
<!ELEMENT redactor (#PCDATA)>
<!ELEMENT fecha (dia, mes, anio)>
	<!ELEMENT dia (#PCDATA)>
	<!ELEMENT mes (#PCDATA)>
	<!ELEMENT anio (#PCDATA)>
<!ELEMENT vidaUtil (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT listaAlternativas (alternativaProyEIA)*>
<!ELEMENT nombreAlternativa (#PCDATA)>
<!ELEMENT listaFactores (factor)+>
		<!ELEMENT factor (nombreFactor,peso?,listaFactores?)>
		<!ELEMENT nombreFactor (#PCDATA)>
		<!ELEMENT peso (#PCDATA)>
<!ELEMENT valorTotal (#PCDATA)>

<!ELEMENT alternativaProyEIA (nombreAlt, listaAcciones, listaEfectos?, valorTotalAlternativa?, valorada)>
<!ELEMENT nombreAlt (#PCDATA)>
	<!ATTLIST nombreAlt
	generica (true|false) "false">	
<!ELEMENT listaAcciones (accion)+>
	<!ELEMENT accion (nombreAccion,listaAcciones?)>
	<!ELEMENT nombreAccion (#PCDATA)>

<!ELEMENT listaEfectos (efecto)+>
<!ELEMENT efecto (idEfecto, descripcion, caracter?, idAccion, idFactor, 			        valorSimpleEnjuiciamiento?, valorCuantitativo?,valorCualitativo?, valorTotal?)>
	<!ELEMENT idEfecto (#PCDATA)>
	<!ELEMENT caracter (#PCDATA)>
	<!ELEMENT idAccion (#PCDATA)>
	<!ELEMENT idFactor (#PCDATA)>
	<!ELEMENT valorSimpleEnjuiciamiento (#PCDATA)>
	<!ELEMENT valorCuantitativo (indicador, maxVal, minVal, magnitud)>
		<!ELEMENT indicador (#PCDATA)>
		<!ELEMENT maxVal (#PCDATA)>
		<!ELEMENT minVal (#PCDATA)>
		<!ELEMENT magnitud (#PCDATA)>
	<!ELEMENT valorCualitativo (signo, acumulacion, extension, extensionCritica, intensidad, persistencia, reversibilidad, recuperabilidad, periodicidad, momento, momentoCritico, efectoImp, incidencia)>
		<!ELEMENT signo (#PCDATA)>
		<!ELEMENT acumulacion (#PCDATA)>
		<!ELEMENT extension (#PCDATA)>
		<!ELEMENT extensionCritica (#PCDATA)>
		<!ELEMENT intensidad (#PCDATA)>
		<!ELEMENT persistencia (#PCDATA)>
		<!ELEMENT reversibilidad (#PCDATA)>
		<!ELEMENT recuperabilidad (#PCDATA)>
		<!ELEMENT periodicidad (#PCDATA)>
		<!ELEMENT momento (#PCDATA)>
		<!ELEMENT momentoCritico (#PCDATA)>
		<!ELEMENT efectoImp (#PCDATA)>
		<!ELEMENT incidencia (#PCDATA)>
	
	<!ELEMENT valorada (#PCDATA)>
<!ELEMENT valorTotalAlternativa (#PCDATA)>

=== Moantonio/eia09/EIASwing/src/eia/util/xml/plantillas/proyectoVacio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proyectoEIA SYSTEM ".\proyectoEIA.dtd">
<proyectoEIA>
	<nombre/>
	<descripcion/>
	<promotor/>
	<redactor/>
	<fecha>
		<dia/>
		<mes/>
		<anio/>
	</fecha>
	<vidaUtil/>
	<poblacion/>
	<provincia/>
	<pais/>
	<listaAlternativas/>
	<listaFactores>
		<factor>
			<nombreFactor>SISTEMA FÍSICO NATURAL</nombreFactor>
			<listaFactores>
				<factor>
					<nombreFactor>Medio abiótico</nombreFactor>
					<listaFactores>
						<factor>
							<nombreFactor>Aire</nombreFactor>
							<listaFactores>
								<factor>
									<nombreFactor>Calidad del aire</nombreFactor>
									<peso>30</peso>
								</factor>
								<factor>
									<nombreFactor> Nivel sonoro</nombreFactor>
									<peso>50</peso>
								</factor>
							</listaFactores>
						</factor>
						<factor>
							<nombreFactor>Geología. Geomorfía</nombreFactor>
							<listaFactores>
								<factor>
									<nombreFactor>Relieve</nombreFactor>
									<peso>25</peso>
								</factor>
								<factor>
									<nombreFactor>Recursos culturales (PIGs)</nombreFactor>
									<peso>15</peso>
								</factor>
							</listaFactores>
						</factor>
						<factor>
							<nombreFactor>Suelos</nombreFactor>
							<listaFactores>
								<factor>
									<nombreFactor>Contaminación del suelo</nombreFactor>
									<peso>20</peso>
								</factor>
								<factor>
									<nombreFactor>Capacidad agrológica del suelo</nombreFactor>
									<peso>20</peso>
								</factor>
							</listaFactores>
						</factor>
						<factor>
							<nombreFactor>Aguas superficiales</nombreFactor>
							<peso>40</peso>
						</factor>
						<factor>
							<nombreFactor>Aguas subterráneas</nombreFactor>
							<peso>30</peso>
						</factor>
					</listaFactores>
				</factor>
				<factor>
					<nombreFactor>Medio biótico</nombreFactor>
					<listaFactores>
						<factor>
							<nombreFactor>Vegetación</nombreFactor>
							<listaFactores>
								<factor>
									<nombreFactor>Formaciones vegetales</nombreFactor>
									<peso>100</peso>
								</factor>
								<factor>
									<nombreFactor>Especies singulares</nombreFactor>
									<peso>20</peso>
								</factor>
							</listaFactores>
						</factor>
						<factor>
							<nombreFactor>Fauna</nombreFactor>
							<peso>120</peso>
						</factor>
					</listaFactores>				
				</factor>
				<factor>
					<nombreFactor>Paisaje</nombreFactor>
					<listaFactores>
						<factor>
							<nombreFactor>Calidad. Unidades de paisaje</nombreFactor>
							<peso>40</peso>
						</factor>
						<factor>
							<nombreFactor>Intervisibilidad</nombreFactor>
							<peso>40</peso>
						</factor>
					</listaFactores>
				</factor>
			</listaFactores>
		</factor>
		<factor>
			<nombreFactor>MEDIO SOCIOECONÓMICO</nombreFactor>
			<listaFactores>
				<factor>
					<nombreFactor>Usos del suelo</nombreFactor>
					<listaFactores>
						<factor>
							<nombreFactor>Usos productivos</nombreFactor>
							<peso>55</peso>
						</factor>
						<factor>
							<nombreFactor> Viario rural</nombreFactor>
							<peso>15</peso>
						</factor>
						<factor>
							<nombreFactor> Usos recreativos</nombreFactor>
							<peso>20</peso>
						</factor>
						<factor>
							<nombreFactor> Conservación de la naturaleza</nombreFactor>
							<peso>40</peso>
						</factor>
					</listaFactores>
				</factor>
				<factor>
					<nombreFactor>Población</nombreFactor>
					<listaFactores>
						<factor>
							<nombreFactor>Empleo</nombreFactor>
							<peso>25</peso>
						</factor>
						<factor>
							<nombreFactor>Calidad de vida</nombreFactor>
							<peso>30</peso>
						</factor>
						<factor>
							<nombreFactor>Aceptación social</nombreFactor>
							<peso>15</peso>
						</factor>
					</listaFactores>
				</factor>
				<factor>
					<nombreFactor>Economía</nombreFactor>
					<peso>40</peso>
				</factor>
				<factor>
					<nombreFactor>Infraestructuras y planeamiento urbanístico</nombreFactor>
					<peso>60</peso>
				</factor>
			</listaFactores>
		</factor>
		<factor>
			<nombreFactor>PATRIMONIO CULTURAL</nombreFactor>
			<listaFactores>
				<factor>
					<nombreFactor>Patrimonio histórico artístico</nombreFactor>
					<peso>55</peso>
				</factor>
				<factor>
					<nombreFactor>Arqueología y paleontología</nombreFactor>
					<peso>45</peso>
				</factor>
			</listaFactores>
		</factor>
		<factor>
			<nombreFactor>PROCESOS</nombreFactor>
			<listaFactores>
				<factor>
					<nombreFactor>Erosión</nombreFactor>
					<peso>20</peso>
				</factor>
				<factor>
					<nombreFactor>Inundación</nombreFactor>
					<peso>10</peso>
				</factor>
				<factor>
					<nombreFactor>Incendios</nombreFactor>
					<peso>20</peso>
				</factor>
			</listaFactores>
		</factor>
	</listaFactores>
</proyectoEIA>

=== Moantonio/eia09/EIA09-Swing/proyectos/gravera.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE proyectoEIA SYSTEM "..\plantillas\proyectoEIA.dtd">
<proyectoEIA><nombre>Gravera</nombre><descripcion>IMPACTO AMBIENTAL EN UNA GRAVERA</descripcion><promotor>EIA09 Pruebas</promotor><redactor>Luis &amp; Kike</redactor><fecha><dia>10</dia><mes>01</mes><anio>2009</anio></fecha><vidaUtil>3</vidaUtil><poblacion>Madrid</poblacion><provincia>Madrid</provincia><pais>España</pais><tipo>PERSONALIZADO</tipo><listaAlternativas><alternativaProyEIA><nombreAlt>Alternativa 1</nombreAlt><listaPrincipalAcciones><accion><nombreAccion>Accion 3</nombreAccion></accion><accion><nombreAccion>Accion 2</nombreAccion></accion><accion><nombreAccion>Acción 1</nombreAccion></accion></listaPrincipalAcciones><listaEfectos><efecto><idEfecto>Incremento de ruidos</idEfecto><descripcion>Ruidos de maquinaria</descripcion><caracter>compatible</caracter><idAccion>Acción 1</idAccion><idFactor> Nivel sonoro</idFactor><valorSimpleEnjuiciamiento>significativo</valorSimpleEnjuiciamiento><valorCuantitativo><indicador>435.2</indicador><maxVal>12035.2</maxVal><minVal>0.0</minVal><magnitud>0.036</magnitud></valorCuantitativo><valorCualitativo><signo>-1</signo><acumulacion>3</acumulacion><extension>4</extension><extensionCritica>0</extensionCritica><intensidad>4</intensidad><persistencia>1</persistencia><reversibilidad>1</reversibilidad><recuperabilidad>4</recuperabilidad><periodicidad>0</periodicidad><momento>0</momento><momentoCritico>0</momentoCritico><efectoImp>0</efectoImp><incidencia>-0.344</incidencia></valorCualitativo><valorTotal>-0.619</valorTotal></efecto><efecto><idEfecto>Emisión de polvo y partículas</idEfecto><descripcion>Suciedad emitida por la maquinaria</descripcion><idAccion>Accion 2</idAccion><idFactor>Contaminación del suelo</idFactor><valorSimpleEnjuiciamiento>significativo</valorSimpleEnjuiciamiento></efecto><efecto><idEfecto>Modificación del microclima</idEfecto><descripcion>Por los humos de la maquinaria</descripcion><idAccion>Accion 3</idAccion><idFactor>Relieve</idFactor><valorSimpleEnjuiciamiento>significativo</valorSimpleEnjuiciamiento></efecto></listaEfectos><valorada>false</valorada></alternativaProyEIA></listaAlternativas><listaFactores><factor><nombreFactor>SISTEMA FÍSICO NATURAL</nombreFactor><peso>550</peso><listaFactores><factor><nombreFactor>Medio abiótico</nombreFactor><peso>230</peso><listaFactores><factor><nombreFactor>Aire</nombreFactor><peso>80</peso><listaFactores><factor><nombreFactor>Calidad del aire</nombreFactor><peso>30</peso></factor><factor><nombreFactor> Nivel sonoro</nombreFactor><peso>50</peso></factor></listaFactores></factor><factor><nombreFactor>Geología. Geomorfía</nombreFactor><peso>40</peso><listaFactores><factor><nombreFactor>Relieve</nombreFactor><peso>25</peso></factor><factor><nombreFactor>Recursos culturales (PIGs)</nombreFactor><peso>15</peso></factor></listaFactores></factor><factor><nombreFactor>Suelos</nombreFactor><peso>40</peso><listaFactores><factor><nombreFactor>Contaminación del suelo</nombreFactor><peso>20</peso></factor><factor><nombreFactor>Capacidad agrológica del suelo</nombreFactor><peso>20</peso></factor></listaFactores></factor><factor><nombreFactor>Aguas superficiales</nombreFactor><peso>40</peso></factor><factor><nombreFactor>Aguas subterráneas</nombreFactor><peso>30</peso></factor></listaFactores></factor><factor><nombreFactor>Medio biótico</nombreFactor><peso>240</peso><listaFactores><factor><nombreFactor>Vegetación</nombreFactor><peso>120</peso><listaFactores><factor><nombreFactor>Formaciones vegetales</nombreFactor><peso>100</peso></factor><factor><nombreFactor>Especies singulares</nombreFactor><peso>20</peso></factor></listaFactores></factor><factor><nombreFactor>Fauna</nombreFactor><peso>120</peso></factor></listaFactores></factor><factor><nombreFactor>Paisaje</nombreFactor><peso>80</peso><listaFactores><factor><nombreFactor>Calidad. Unidades de paisaje</nombreFactor><peso>40</peso></factor><factor><nombreFactor>Intervisibilidad</nombreFactor><peso>40</peso></factor></listaFactores></factor></listaFactores></factor><factor><nombreFactor>MEDIO SOCIOECONÓMICO</nombreFactor><peso>300</peso><listaFactores><factor><nombreFactor>Usos del suelo</nombreFactor><peso>130</peso><listaFactores><factor><nombreFactor>Usos productivos</nombreFactor><peso>55</peso></factor><factor><nombreFactor> Viario rural</nombreFactor><peso>15</peso></factor><factor><nombreFactor> Usos recreativos</nombreFactor><peso>20</peso></factor><factor><nombreFactor> Conservación de la naturaleza</nombreFactor><peso>40</peso></factor></listaFactores></factor><factor><nombreFactor>Población</nombreFactor><peso>70</peso><listaFactores><factor><nombreFactor>Empleo</nombreFactor><peso>25</peso></factor><factor><nombreFactor>Calidad de vida</nombreFactor><peso>30</peso></factor><factor><nombreFactor>Aceptación social</nombreFactor><peso>15</peso></factor></listaFactores></factor><factor><nombreFactor>Economía</nombreFactor><peso>40</peso></factor><factor><nombreFactor>Infraestructuras y planeamiento urbanístico</nombreFactor><peso>60</peso></factor></listaFactores></factor><factor><nombreFactor>PATRIMONIO CULTURAL</nombreFactor><peso>100</peso><listaFactores><factor><nombreFactor>Patrimonio histórico artístico</nombreFactor><peso>55</peso></factor><factor><nombreFactor>Arqueología y paleontología</nombreFactor><peso>45</peso></factor></listaFactores></factor><factor><nombreFactor>PROCESOS</nombreFactor><peso>50</peso><listaFactores><factor><nombreFactor>Erosión</nombreFactor><peso>20</peso></factor><factor><nombreFactor>Inundación</nombreFactor><peso>10</peso></factor><factor><nombreFactor>Incendios</nombreFactor><peso>20</peso></factor></listaFactores></factor></listaFactores></proyectoEIA>

=== Moantonio/eia09/EIASwing/plantillas/pruebas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE proyectoEIA SYSTEM ".\proyectoEIA.dtd">
<proyectoEIA><nombre>proyecto</nombre><descripcion/><promotor/><redactor/><fecha><dia>02</dia><mes>01</mes><anio>2009</anio></fecha><vidaUtil>0</vidaUtil><poblacion/><provincia/><pais/><tipo>PRESA</tipo><listaAlternativas><alternativaProyEIA><nombreAlt>x</nombreAlt><listaPrincipalAcciones><accion><nombreAccion>Fase de Planeamiento</nombreAccion><listaAcciones><accion><nombreAccion>Diseño y localización de alternativas</nombreAccion></accion></listaAcciones></accion><accion><nombreAccion>Fase de Construcción</nombreAccion><listaAcciones><accion><nombreAccion>Desviación de aguas y ataguías</nombreAccion></accion><accion><nombreAccion>Caminos y pistas de acceso y montaje</nombreAccion></accion><accion><nombreAccion>Infraestructuras</nombreAccion><listaAcciones><accion><nombreAccion>Líneas de transporte eléctrico</nombreAccion></accion><accion><nombreAccion>Canales</nombreAccion></accion><accion><nombreAccion>Conducciones de agua</nombreAccion></accion></listaAcciones></accion><accion><nombreAccion>Obras de construcción propiamente dichas</nombreAccion></accion><accion><nombreAccion>Transporte de materiales</nombreAccion></accion><accion><nombreAccion>Movimiento de maquinaria pesada</nombreAccion></accion><accion><nombreAccion>Vertido de tierras y otros materiales</nombreAccion></accion><accion><nombreAccion>Edificios de obra</nombreAccion></accion><accion><nombreAccion>Deforestación del vaso</nombreAccion></accion><accion><nombreAccion>Explotación canteras</nombreAccion></accion><accion><nombreAccion>Reposición de viales destruidos o inundados</nombreAccion></accion><accion><nombreAccion>Expropiaciones</nombreAccion></accion><accion><nombreAccion>Incremento de la mano de obra</nombreAccion></accion></listaAcciones></accion><accion><nombreAccion>Fase de Funcionamiento</nombreAccion><listaAcciones><accion><nombreAccion>Presa y embalsamado del agua</nombreAccion></accion><accion><nombreAccion>Infraestructuras  </nombreAccion></accion><accion><nombreAccion>Oscilaciones del nivel de agua embalsada</nombreAccion></accion><accion><nombreAccion>Regulación del caudal de aguas abajo de la presa</nombreAccion></accion></listaAcciones></accion></listaPrincipalAcciones><listaEfectos><efecto><idEfecto>x1</idEfecto><descripcion/><idAccion>Diseño y localización de alternativas</idAccion><idFactor>Inundación</idFactor><valorSimpleEnjuiciamiento>despreciable</valorSimpleEnjuiciamiento></efecto><efecto><idEfecto>x2</idEfecto><descripcion/><caracter>compatible</caracter><idAccion>Regulación del caudal de aguas abajo de la presa</idAccion><idFactor>Arqueología y paleontología</idFactor><valorSimpleEnjuiciamiento>despreciable</valorSimpleEnjuiciamiento><valorCuantitativo><indicador>2.0</indicador><maxVal>12.0</maxVal><minVal>1.0</minVal><magnitud>0.091</magnitud></valorCuantitativo><valorCualitativo><signo>1</signo><acumulacion>0</acumulacion><extension>2</extension><extensionCritica>0</extensionCritica><intensidad>0</intensidad><persistencia>0</persistencia><reversibilidad>0</reversibilidad><recuperabilidad>0</recuperabilidad><periodicidad>1</periodicidad><momento>0</momento><momentoCritico>0</momentoCritico><efectoImp>0</efectoImp><incidencia>0.125</incidencia></valorCualitativo><valorTotal>0.512</valorTotal></efecto></listaEfectos><valorada>false</valorada></alternativaProyEIA><alternativaProyEIA><nombreAlt>y</nombreAlt><listaPrincipalAcciones><accion><nombreAccion>Fase de Planeamiento</nombreAccion><listaAcciones><accion><nombreAccion>Diseño y localización de alternativas</nombreAccion></accion></listaAcciones></accion><accion><nombreAccion>Fase de Construcción</nombreAccion><listaAcciones><accion><nombreAccion>Desviación de aguas y ataguías</nombreAccion></accion><accion><nombreAccion>Caminos y pistas de acceso y montaje</nombreAccion></accion><accion><nombreAccion>Infraestructuras</nombreAccion><listaAcciones><accion><nombreAccion>Líneas de transporte eléctrico</nombreAccion></accion><accion><nombreAccion>Canales</nombreAccion></accion><accion><nombreAccion>Conducciones de agua</nombreAccion></accion></listaAcciones></accion><accion><nombreAccion>Obras de construcción propiamente dichas</nombreAccion></accion><accion><nombreAccion>Transporte de materiales</nombreAccion></accion><accion><nombreAccion>Movimiento de maquinaria pesada</nombreAccion></accion><accion><nombreAccion>Vertido de tierras y otros materiales</nombreAccion></accion><accion><nombreAccion>Edificios de obra</nombreAccion></accion><accion><nombreAccion>Deforestación del vaso</nombreAccion></accion><accion><nombreAccion>Explotación canteras</nombreAccion></accion><accion><nombreAccion>Reposición de viales destruidos o inundados</nombreAccion></accion><accion><nombreAccion>Expropiaciones</nombreAccion></accion><accion><nombreAccion>Incremento de la mano de obra</nombreAccion></accion></listaAcciones></accion></listaPrincipalAcciones><listaEfectos><efecto><idEfecto>y1</idEfecto><descripcion/><idAccion>Caminos y pistas de acceso y montaje</idAccion><idFactor>Economía</idFactor><valorSimpleEnjuiciamiento>despreciable</valorSimpleEnjuiciamiento></efecto></listaEfectos><valorada>false</valorada></alternativaProyEIA><alternativaProyEIA><nombreAlt>z</nombreAlt><listaPrincipalAcciones><accion><nombreAccion>Fase de Funcionamiento</nombreAccion><listaAcciones><accion><nombreAccion>Presa y embalsamado del agua</nombreAccion></accion><accion><nombreAccion>Infraestructuras  </nombreAccion></accion><accion><nombreAccion>Oscilaciones del nivel de agua embalsada</nombreAccion></accion><accion><nombreAccion>Regulación del caudal de aguas abajo de la presa</nombreAccion></accion></listaAcciones></accion></listaPrincipalAcciones><listaEfectos><efecto><idEfecto>z1</idEfecto><descripcion/><idAccion>Presa y embalsamado del agua</idAccion><idFactor>Calidad del aire</idFactor><valorSimpleEnjuiciamiento>despreciable</valorSimpleEnjuiciamiento></efecto><efecto><idEfecto>z2</idEfecto><descripcion/><idAccion>Oscilaciones del nivel de agua embalsada</idAccion><idFactor>Calidad. Unidades de paisaje</idFactor><valorSimpleEnjuiciamiento>despreciable</valorSimpleEnjuiciamiento></efecto></listaEfectos><valorada>false</valorada></alternativaProyEIA></listaAlternativas><listaFactores><factor><nombreFactor>SISTEMA FÍSICO NATURAL</nombreFactor><peso>30</peso><listaFactores><factor><nombreFactor>Medio abiótico</nombreFactor><peso>30</peso><listaFactores><factor><nombreFactor>Aire</nombreFactor><peso>30</peso><listaFactores><factor><nombreFactor>Calidad del aire</nombreFactor><peso>30</peso></factor><factor><nombreFactor> Nivel sonoro</nombreFactor><peso>50</peso></factor></listaFactores></factor><factor><nombreFactor>Geología. Geomorfía</nombreFactor><peso>25</peso><listaFactores><factor><nombreFactor>Relieve</nombreFactor><peso>25</peso></factor><factor><nombreFactor>Recursos culturales (PIGs)</nombreFactor><peso>15</peso></factor></listaFactores></factor><factor><nombreFactor>Suelos</nombreFactor><peso>20</peso><listaFactores><factor><nombreFactor>Contaminación del suelo</nombreFactor><peso>20</peso></factor><factor><nombreFactor>Capacidad agrológica del suelo</nombreFactor><peso>20</peso></factor></listaFactores></factor><factor><nombreFactor>Aguas superficiales</nombreFactor><peso>40</peso></factor><factor><nombreFactor>Aguas subterráneas</nombreFactor><peso>30</peso></factor></listaFactores></factor><factor><nombreFactor>Medio biótico</nombreFactor><peso>100</peso><listaFactores><factor><nombreFactor>Vegetación</nombreFactor><peso>100</peso><listaFactores><factor><nombreFactor>Formaciones vegetales</nombreFactor><peso>100</peso></factor><factor><nombreFactor>Especies singulares</nombreFactor><peso>20</peso></factor></listaFactores></factor><factor><nombreFactor>Fauna</nombreFactor><peso>120</peso></factor></listaFactores></factor><factor><nombreFactor>Paisaje</nombreFactor><peso>40</peso><listaFactores><factor><nombreFactor>Calidad. Unidades de paisaje</nombreFactor><peso>40</peso></factor><factor><nombreFactor>Intervisibilidad</nombreFactor><peso>40</peso></factor></listaFactores></factor></listaFactores></factor><factor><nombreFactor>MEDIO SOCIOECONÓMICO</nombreFactor><peso>55</peso><listaFactores><factor><nombreFactor>Usos del suelo</nombreFactor><peso>55</peso><listaFactores><factor><nombreFactor>Usos productivos</nombreFactor><peso>55</peso></factor><factor><nombreFactor> Viario rural</nombreFactor><peso>15</peso></factor><factor><nombreFactor> Usos recreativos</nombreFactor><peso>20</peso></factor><factor><nombreFactor> Conservación de la naturaleza</nombreFactor><peso>40</peso></factor></listaFactores></factor><factor><nombreFactor>Población</nombreFactor><peso>25</peso><listaFactores><factor><nombreFactor>Empleo</nombreFactor><peso>25</peso></factor><factor><nombreFactor>Calidad de vida</nombreFactor><peso>30</peso></factor><factor><nombreFactor>Aceptación social</nombreFactor><peso>15</peso></factor></listaFactores></factor><factor><nombreFactor>Economía</nombreFactor><peso>40</peso></factor><factor><nombreFactor>Infraestructuras y planeamiento urbanístico</nombreFactor><peso>60</peso></factor></listaFactores></factor><factor><nombreFactor>PATRIMONIO CULTURAL</nombreFactor><peso>55</peso><listaFactores><factor><nombreFactor>Patrimonio histórico artístico</nombreFactor><peso>55</peso></factor><factor><nombreFactor>Arqueología y paleontología</nombreFactor><peso>45</peso></factor></listaFactores></factor><factor><nombreFactor>PROCESOS</nombreFactor><peso>20</peso><listaFactores><factor><nombreFactor>Erosión</nombreFactor><peso>20</peso></factor><factor><nombreFactor>Inundación</nombreFactor><peso>10</peso></factor><factor><nombreFactor>Incendios</nombreFactor><peso>20</peso></factor></listaFactores></factor></listaFactores></proyectoEIA>
